language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
  - php composer.phar require --dev php-coveralls/php-coveralls
script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/php-coveralls -v