language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer install
  - composer require satooshi/php-coveralls --prefer-dist

script: phpunit

after_script: php vendor/bin/coveralls -v
